Transition to quizpage
jigintern/2023-summer-d pull request #15
Opened 2023-08-17 06:42 UTC by Daisuke0655

デザインの変更
typhoonQuiz.htmlへ遷移できるように

2023-08-17 07:15 UTC, NKMAK approved these changes
確認しました

2023-08-17 08:54 UTC, Daisuke0655 commented
修正したので確認をお願いします。

2023-08-18 00:24 UTC, haruyuki-16278 requested changes
一個だけ構文的な指摘したいです :bow:

2023-08-18 00:24 UTC, haruyuki-16278 commented on public/index.css
> +.title-widget>h1{
```suggestion
.title-widget>h1 {
```

2023-08-18 00:29 UTC, haruyuki-16278 approved these changes
サジェストだけ適用してもらえれば大丈夫だと思います！  
LGTM :+1:

2023-08-18 00:32 UTC, merged