end.jsonとquiz.jsonに変更有
jigintern/2023-summer-d pull request #8
Opened 2023-08-16 08:29 UTC by TsuruKtakumi

2023-08-16 10:15 UTC, NKMAK approved these changes
確認しました。
追加のシナリオありがとうございます！

2023-08-17 00:27 UTC, haruyuki-16278 requested changes
気になること他にもあるんですけど一旦コメントした内容を確認してほしいです。

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/end.json
> +        "isGoodEnd": true
```suggestion
        "message": "川の近くを通って避難していたあなただったが、氾濫した川の流れに押し流され、死んでしまった...",
        "isGoodEnd": false
    },
    {
        "message": "斜面の近くを通って避難していたあなただったが、土砂崩れに巻き込まれて死んでしまった...",
        "isGoodEnd": false
    },
    {
        "message": "来た道を引き返したあなただったが、一次戻ったことで台風の勢いが増してしまい、濁流にのみ込まれて死んでしまった...",
        "isGoodEnd": false
    },
    {
        "message": "姿勢が高いまま移動してしまったあなたは、強風に吹き飛ばされ、地面に強く体を打ち付けて死んでしまった...",
        "isGoodEnd": false
    },
    {
        "message": "あなたは数々の苦難を乗り越えて避難所へたどり着いた。おめでとう！",
        "isGoodEnd": true
```

プロパティ名の後ろの`:`と値の間にはスペース入れてほしい気がします。

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    "destination":{
```suggestion
    "advice": "強い風に煽られた物が飛んで来る可能性があるので、窓が割れないように対策しましょう。",
    "destination": {
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +      "C":2
```suggestion
    "advice": "停電や食料の枯渇に備え、物資を準備しておくようにしましょう。",
    "destination": {
      "A": "e-1",
      "B": "負傷",
      "C": 2
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +      "C":"負傷"
```suggestion
    "advice": "風で飛ばされたものは凶器になりうるので、固定するか家の中にしまいましょう。",
    "destination": {
      "A": "負傷",
      "B": 3,
      "C": "負傷"
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "スムーズに避難できるよう、事前に避難所など確認しておきましょう。",
    "destination": {
      "A": "負傷",
      "B": "負傷",
      "C": 4
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "台風に限らず、災害が発生した際は早めの行動を心掛けましょう。",
    "destination": {
      "A": "負傷",
      "B": "e-2",
      "C": 5
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "車は水没すると動けなくなり、電車は災害時は運休することが多いので、徒歩で避難するようにしましょう。",
    "destination": {
      "A": 6,
      "B": "e-3",
      "C": "負傷"
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "川の近くは氾濫、斜面の近くは土砂崩れに巻き込まれる恐れがあるので、高いところにある道路から避難しましょう。",
    "destination": {
      "A": "e-4",
      "B": 7,
      "C": "e-5"
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "冠水した道路では足元が見えにくく危険なので、冠水していない道路を通るようにしましょう。\nまた、避難時に引き返すのはとても危険です。絶対にやめましょう。",
    "destination": {
      "A": 8,
      "B": "負傷",
      "C": "e-6"
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "足元が見えにくい場合、ふたの空いたマンホールや側溝に落ちる恐れがあり危険です。\n長い棒状のものが手元にある場合、足元を探りながら歩きましょう。",
    "destination": {
      "A": "負傷",
      "B": 9,
      "C": "負傷"
    }
```

2023-08-17 00:27 UTC, haruyuki-16278 commented on public/quiz.json
> +    }
```suggestion
    "advice": "姿勢が高かったり、風に逆らったりすると、風に飛ばされてしまう恐れがあります。\n姿勢を低くして避難しましょう。",
    "destination": {
      "A": "e-7",
      "B": "e-8",
      "C": "e-7"
    }
```

2023-08-17 01:17 UTC, haruyuki-16278 requested changes
JSONの構造のより良さそうなものをコメントしたので確認・対応お願いしたいです。

2023-08-17 01:17 UTC, haruyuki-16278 commented on public/quiz.json
> +      "C": 5
```
    "question": "問題文",
    "choices": {
      "A": {
        "text": "選択肢の内容",
        "isCorrect": true,
        "dest": 1,
        "damaged": true
      },
      "B": {
        "text": "選択肢の内容",
        "isCorrect": true,
        "dest": 1,
        "damaged": true
      },
      "C": {
        "text": "選択肢の内容",
        "isCorrect": true,
        "dest": 1,
        "damaged": true
      }
    },
    "advice": ""
```

一問のjsonの形がこんなふうになってると扱いやすいような気がしたので、これで対応お願いします。

2023-08-17 02:34 UTC, haruyuki-16278 approved these changes
ぱっと見これでいいと思います。

2023-08-17 02:35 UTC, merged